version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./web/python/DockerFile
    container_name: 'app-web'
    volumes:
      - .:/application
    expose:
      - 8000
    depends_on:
      - postgres_db
    networks:
      - web

  postgres_db:
    image: postgres:13-alpine
    container_name: 'app-db'
    environment:
      - POSTGRES_USER=stepan
      - POSTGRES_PASSWORD=19982804
      - POSTGRES_DB=posttitle
    volumes:
      - ./web/postgres:/var/lib/postgresql/data
    networks:
      - web

  nginx:
    container_name: 'app-nginx'
    image: nginx:alpine
    build: ./web/nginx
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - .:/application
    networks:
      - web


networks:
  web:
    driver: bridge