version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./web/python/DockerFile
    container_name: 'app-web3'
    volumes:
      - .:/application
    expose:
      - 5432
    depends_on:
      - postgres_db
    networks:
      - app

  postgres_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=stepan
      - POSTGRES_PASSWORD=19982804
      - POSTGRES_DB=posttitle
    volumes:
      - ./web/postgres:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    driver: bridge